language: lisp
sudo: false

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t
  matrix:
#     - LISP=sbcl-bin COVERALLS=true
    - LISP=sbcl-bin
    - LISP=ccl-bin

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - (cd ${ROSWELL_INSTALL_DIR}/local-projects ; git clone https://github.com/eshamster/ps-experiment.git)
  - (cd ${ROSWELL_INSTALL_DIR}/local-projects ; git clone https://github.com/eshamster/cl-ps-ecs.git)
  - ros -e '(ql:register-local-projects)' -q
  - ros install prove

script:
  - run-prove *-test.asd

